
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:87s61/eureka
    instance:
        hostname: localhost
